
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using Oracle.ManagedDataAccess.Client;
using Oracle.ManagedDataAccess.Types;


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [Key]
        public int Indext { get; set; }
        public string Color { get; set; }
    }

    public class SQLServerConnectionString: DbContext
    {
        public DbSet<Test> Colors {get; set;}
    }

    public class SQLExpressConnectionString : DbContext
    {
        public DbSet<Test> Colors { get; set; }
    }

    //[Table("Tests", Schema = "KAMURAI")]
    public class OracleConnectionString : DbContext
    {
        public DbSet<Test> Colors { get; set; }
    }

    public class MySQLConnectionString : DbContext
    {
        public DbSet<Test> Colors { get; set; }
    }

    //[Table("Tests", Schema = "Public")]
    public class PostgreSQLConnectionString : DbContext
    {
        public DbSet<Test> Colors { get; set; }
    }
}
